In [1]:
import matplotlib.pyplot as plt

from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split

digits = datasets.load_digits()
n_samples = len(digits.images)
data = digits.images.reshape((n_samples, -1))

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6)

X_train, X_test, y_train, y_test = train_test_split(
    data, digits.target, test_size=0.2)

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [3]:

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.8444444444444444
[[31  0  0  0  0  1  1  0  2  0]
 [ 0 31  0  0  0  0  0  0  5  2]
 [ 0  2 27  2  0  0  0  0  0  1]
 [ 0  0  1 22  0  0  1  0  0  1]
 [ 0  1  0  1 26  0  1  1  0  1]
 [ 0  0  1  0  2 34  0  0  2  1]
 [ 0  0  0  0  0  0 36  0  2  0]
 [ 0  1  0  1  0  1  2 35  1  0]
 [ 0  3  1  1  0  4  0  1 31  3]
 [ 0  0  0  1  0  0  0  0  4 31]]


In [4]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9583333333333334
[[34  0  0  0  0  0  1  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 24  0  1  0  0  0  0]
 [ 0  0  0  0 30  0  0  1  0  0]
 [ 0  0  1  1  0 38  0  0  0  0]
 [ 0  0  0  0  0  0 37  0  1  0]
 [ 0  0  0  0  1  0  0 40  0  0]
 [ 0  1  1  0  0  2  0  0 39  1]
 [ 0  0  0  2  0  0  0  0  1 33]]


C:\Users\User\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9694444444444444
[[34  0  0  0  1  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  1  0  0]
 [ 0  0  0  0  1 39  0  0  0  0]
 [ 0  0  0  0  0  0 37  0  1  0]
 [ 0  0  0  0  0  0  0 41  0  0]
 [ 0  1  0  2  0  0  0  1 40  0]
 [ 0  0  0  0  1  1  0  0  1 33]]


In [6]:
from sklearn.neighbors import KNeighborsClassifier

# 대충 k값 5
clf_knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust the number of neighbors (k) as needed
clf_knn.fit(X_train, y_train)

pred_knn = clf_knn.predict(X_test)

print("\n--- K-Nearest Neighbors (KNN) Classifier ---")
print("Accuracy:", accuracy_score(y_test, pred_knn))
print("Confusion Matrix:")
print(confusion_matrix(y_test, pred_knn))


--- K-Nearest Neighbors (KNN) Classifier ---
Accuracy: 0.9777777777777777
Confusion Matrix:
[[34  0  0  0  1  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0  0 32  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  1  0  0]
 [ 0  0  0  0  0 40  0  0  0  0]
 [ 0  1  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 41  0  0]
 [ 0  1  0  1  0  0  0  0 42  0]
 [ 0  0  0  0  1  1  0  0  1 33]]
