In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("C:/AI/PAMAP_features.csv", index_col=0)
df

sub_id  activity_id act_level     hr_mean  hr_mean_normal    hr_std  \
3006        2           17     light   87.000000        1.175676  0.000000   
3497        2            4  moderate  124.605469        1.683858  0.927920   
14495       7            5  vigorous  113.493430        1.891557  2.315888   
13278       7           17     light   82.513672        1.375228  0.492657   
14969       8            3     light   73.000000        1.106061  0.000000   
...       ...          ...       ...         ...             ...       ...   
10708       6            2     light   82.582031        1.376367  0.930285   
4870        3            2     light   76.998047        1.132324  0.806906   
11822       6            4  moderate   93.445312        1.557422  0.493415   
3866        2            7  moderate  129.160156        1.745408  0.361877   
3450        2           13  moderate  142.234375        1.922086  1.714464   

       hr_std_normal  hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  ...  \
3006    7.105427e-15      34.375000      0.000000        -1.165524  ...   
3497    1.253946e-02      31.875000      0.000000       -12.040995  ...   
14495   3.859813e-02      32.500000      0.000000        -3.723040  ...   
13278   8.210948e-03      33.812500      0.000000        -3.618932  ...   
14969   7.327472e-15      34.437500      0.000000        -9.275877  ...   
...              ...            ...           ...              ...  ...   
10708   1.550475e-02      33.525635      0.030741        -4.306831  ...   
4870    1.186626e-02      32.083130      0.029390        -1.545991  ...   
11822   8.223580e-03      31.750000      0.000000       -10.034760  ...   
3866    4.890232e-03      30.465576      0.031088        -8.275569  ...   
3450    2.316843e-02      32.173340      0.026163        -3.077000  ...   

       ankle_acc_xz_cor  hand_gyr_xy_cor  hand_gyr_yz_cor  hand_gyr_xz_cor  \
3006           0.233251        -0.472662         0.335516        -0.377507   
3497          -0.119772        -0.287380        -0.230390        -0.491314   
14495          0.025673        -0.265566         0.824691        -0.121345   
13278          0.724061        -0.196728         0.315984        -0.380337   
14969         -0.001651        -0.060776         0.165672         0.311760   
...                 ...              ...              ...              ...   
10708          0.193950        -0.354026         0.175876        -0.172933   
4870           0.135629         0.056979         0.008235         0.001093   
11822         -0.404942         0.520845        -0.951838        -0.561901   
3866          -0.136336        -0.147614        -0.344375        -0.329746   
3450           0.200755        -0.081262         0.130816        -0.278256   

       chest_gyr_xy_cor  chest_gyr_yz_cor  chest_gyr_xz_cor  ankle_gyr_xy_cor  \
3006          -0.290138         -0.779952          0.071855         -0.305959   
3497           0.011124         -0.799319         -0.135736         -0.653133   
14495         -0.004923         -0.317761         -0.202148         -0.660278   
13278          0.284190         -0.109078         -0.071734         -0.177813   
14969         -0.272620         -0.014943         -0.191610         -0.261158   
...                 ...               ...               ...               ...   
10708          0.184131         -0.274344         -0.485489         -0.100010   
4870          -0.203294         -0.097797         -0.273316         -0.009717   
11822         -0.169119          0.299434         -0.100683         -0.555866   
3866          -0.024487         -0.536806         -0.161019         -0.752563   
3450          -0.254757         -0.723943         -0.039044         -0.016410   

       ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006          -0.003001         -0.638866  
3497          -0.654575          0.391363  
14495         -0.528138          0.402147  
13278          0.237828         -0.729771  
14969          0.066954          0.0576

In [2]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
label=LabelEncoder()

df['sub_id']=label.fit_transform(df['sub_id'])
df['act_level']=label.fit_transform(df['act_level'])
df.head()

sub_id  activity_id  act_level     hr_mean  hr_mean_normal    hr_std  \
3006        1           17          0   87.000000        1.175676  0.000000   
3497        1            4          1  124.605469        1.683858  0.927920   
14495       6            5          2  113.493430        1.891557  2.315888   
13278       6           17          0   82.513672        1.375228  0.492657   
14969       7            3          0   73.000000        1.106061  0.000000   

       hr_std_normal  hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  ...  \
3006    7.105427e-15        34.3750           0.0        -1.165524  ...   
3497    1.253946e-02        31.8750           0.0       -12.040995  ...   
14495   3.859813e-02        32.5000           0.0        -3.723040  ...   
13278   8.210948e-03        33.8125           0.0        -3.618932  ...   
14969   7.327472e-15        34.4375           0.0        -9.275877  ...   

       ankle_acc_xz_cor  hand_gyr_xy_cor  hand_gyr_yz_cor  hand_gyr_xz_cor  \
3006           0.233251        -0.472662         0.335516        -0.377507   
3497          -0.119772        -0.287380        -0.230390        -0.491314   
14495          0.025673        -0.265566         0.824691        -0.121345   
13278          0.724061        -0.196728         0.315984        -0.380337   
14969         -0.001651        -0.060776         0.165672         0.311760   

       chest_gyr_xy_cor  chest_gyr_yz_cor  chest_gyr_xz_cor  ankle_gyr_xy_cor  \
3006          -0.290138         -0.779952          0.071855         -0.305959   
3497           0.011124         -0.799319         -0.135736         -0.653133   
14495         -0.004923         -0.317761         -0.202148         -0.660278   
13278          0.284190         -0.109078         -0.071734         -0.177813   
14969         -0.272620         -0.014943         -0.191610         -0.261158   

       ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006          -0.003001         -0.638866  
3497          -0.654575          0.391363  
14495         -0.528138          0.402147  
13278          0.237828         -0.729771  
14969          0.066954          0.057685  

[5 rows x 67 columns]

In [3]:
# 결측치 확인
df.isnull().sum()

sub_id              0
activity_id         0
act_level           0
hr_mean             0
hr_mean_normal      0
                   ..
chest_gyr_yz_cor    0
chest_gyr_xz_cor    0
ankle_gyr_xy_cor    0
ankle_gyr_yz_cor    0
ankle_gyr_xz_cor    0
Length: 67, dtype: int64

In [4]:
import seaborn as sns

import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix

In [5]:
# 각 열의 레이블 확인 및 개수 세기
for column in df.columns:
    print(f"Column: {column}")
    print(df[column].value_counts())
    print()

Column: sub_id
sub_id
4    1651
1    1618
7    1576
5    1556
0    1518
6    1430
3    1353
2    1042
8      29
Name: count, dtype: int64

Column: activity_id
activity_id
17    1539
4     1525
3     1220
1     1203
7     1196
2     1162
16    1099
6     1035
5      593
12     522
13     428
24     251
Name: count, dtype: int64

Column: act_level
act_level
1    5283
0    5124
2    1366
Name: count, dtype: int64

Column: hr_mean
hr_mean
119.000000    81
124.000000    77
120.000000    66
79.000000     59
71.000000     56
              ..
71.101562      1
125.919922     1
80.703125      1
129.625000     1
142.234375     1
Name: count, Length: 8979, dtype: int64

Column: hr_mean_normal
hr_mean_normal
1.750000    51
1.000000    35
1.878788    35
1.090909    29
1.600000    27
            ..
1.230022     1
2.123165     1
1.859931     1
2.183392     1
1.922086     1
Name: count, Length: 9923, dtype: int64

Column: hr_std
hr_std
0.000000    2031
0.457374      89
0.466765      67
0.492707      35

In [6]:
X=df.drop(['sub_id', 'activity_id'],axis=1)
X.head()

act_level     hr_mean  hr_mean_normal    hr_std  hr_std_normal  \
3006           0   87.000000        1.175676  0.000000   7.105427e-15   
3497           1  124.605469        1.683858  0.927920   1.253946e-02   
14495          2  113.493430        1.891557  2.315888   3.859813e-02   
13278          0   82.513672        1.375228  0.492657   8.210948e-03   
14969          0   73.000000        1.106061  0.000000   7.327472e-15   

       hand_tmp_mean  hand_tmp_std  hand_acc_x_mean  hand_acc_x_std  \
3006         34.3750           0.0        -1.165524        2.383779   
3497         31.8750           0.0       -12.040995        3.734766   
14495        32.5000           0.0        -3.723040       10.188184   
13278        33.8125           0.0        -3.618932        1.935690   
14969        34.4375           0.0        -9.275877        0.082824   

       hand_acc_y_mean  ...  ankle_acc_xz_cor  hand_gyr_xy_cor  \
3006          3.381285  ...          0.233251        -0.472662   
3497          3.069947  ...         -0.119772        -0.287380   
14495        11.705779  ...          0.025673        -0.265566   
13278         0.542981  ...          0.724061        -0.196728   
14969         1.006239  ...         -0.001651        -0.060776   

       hand_gyr_yz_cor  hand_gyr_xz_cor  chest_gyr_xy_cor  chest_gyr_yz_cor  \
3006          0.335516        -0.377507         -0.290138         -0.779952   
3497         -0.230390        -0.491314          0.011124         -0.799319   
14495         0.824691        -0.121345         -0.004923         -0.317761   
13278         0.315984        -0.380337          0.284190         -0.109078   
14969         0.165672         0.311760         -0.272620         -0.014943   

       chest_gyr_xz_cor  ankle_gyr_xy_cor  ankle_gyr_yz_cor  ankle_gyr_xz_cor  
3006           0.071855         -0.305959         -0.003001         -0.638866  
3497          -0.135736         -0.653133         -0.654575          0.391363  
14495         -0.202148         -0.660278         -0.528138          0.402147  
13278         -0.071734         -0.177813          0.237828         -0.729771  
14969         -0.191610         -0.261158          0.066954          0.057685  

[5 rows x 65 columns]

In [7]:
y=df['sub_id']
y.value_counts()

sub_id
4    1651
1    1618
7    1576
5    1556
0    1518
6    1430
3    1353
2    1042
8      29
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(9418, 65) (2355, 65) (9418,) (2355,)


In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import warnings
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [18]:
print("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)


--- Random Forest ---


In [19]:
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       304
           1       1.00      1.00      1.00       337
           2       1.00      1.00      1.00       205
           3       1.00      1.00      1.00       274
           4       1.00      1.00      1.00       339
           5       1.00      1.00      1.00       300
           6       1.00      1.00      1.00       288
           7       1.00      1.00      1.00       303
           8       1.00      1.00      1.00         5

    accuracy                           1.00      2355
   macro avg       1.00      1.00      1.00      2355
weighted avg       1.00      1.00      1.00      2355

[[304   0   0   0   0   0   0   0   0]
 [  0 337   0   0   0   0   0   0   0]
 [  0   0 205   0   0   0   0   0   0]
 [  0   0   0 274   0   0   0   0   0]
 [  0   0   0   0 339   0   0   0   0]
 [  0   0   0   0   0 300   0   0   0]
 [  0   0   0   0   0   0 288   0   0]
 [  0   0   0   0   0 

In [21]:
print(classification_report(y_test, pred))
print(confusion_matrix(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       304
           1       1.00      1.00      1.00       337
           2       1.00      1.00      1.00       205
           3       1.00      1.00      1.00       274
           4       1.00      1.00      1.00       339
           5       1.00      1.00      1.00       300
           6       1.00      1.00      1.00       288
           7       1.00      1.00      1.00       303
           8       1.00      1.00      1.00         5

    accuracy                           1.00      2355
   macro avg       1.00      1.00      1.00      2355
weighted avg       1.00      1.00      1.00      2355

[[304   0   0   0   0   0   0   0   0]
 [  0 337   0   0   0   0   0   0   0]
 [  0   0 205   0   0   0   0   0   0]
 [  0   0   0 274   0   0   0   0   0]
 [  0   0   0   0 339   0   0   0   0]
 [  0   0   0   0   0 300   0   0   0]
 [  0   0   0   0   0   0 288   0   0]
 [  0   0   0   0   0 

In [22]:

import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(classification_report(y_test,pred_dt))
print(confusion_matrix(y_test,pred_dt))


--- Radom Forest ---
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       304
           1       1.00      1.00      1.00       337
           2       0.99      1.00      0.99       205
           3       0.98      0.99      0.98       274
           4       1.00      1.00      1.00       339
           5       1.00      0.99      0.99       300
           6       1.00      1.00      1.00       288
           7       1.00      0.99      1.00       303
           8       1.00      1.00      1.00         5

    accuracy                           0.99      2355
   macro avg       0.99      0.99      0.99      2355
weighted avg       0.99      0.99      0.99      2355

[[299   0   0   4   0   1   0   0   0]
 [  0 337   0   0   0   0   0   0   0]
 [  0   0 204   0   0   0   1   0   0]
 [  2   0   1 271   0   0   0   0   0]
 [  0   0   0   0 339   0   0   0   0]
 [  0   0   2   0   0 298   0   0   0]
 [  0   0   0   0   0   0 288   0   0]
